### ISSUE TITLE
Word art browser IE doesn't work (Beta version 0.10.10-a)

### ISSUE THREAD

**Issue by jeroensomers** [Doodle3D/doodle3d-client#301] opened 2016-02-29 14:56 UTC
In the browser IE on the laptop the function WORD ART doesn't work.
when you type something, anything at all, it won't appear on the screen.

**Comment by peteruithoven** [comment] 2016-02-29 15:25
The text does appear in the popup? So it doesn't appear in the drawing area? Could you check (copy) the contents of the Web console?

**Comment by companje** [comment] 2016-02-29 19:16
I think this issue is a duplicate of this one: #267

**Comment by jeroensomers** [comment] 2016-03-02 15:57
This is what the Web console says: **"sketch: isModified true curSketch 2 sketches.length 3"**

**Comment by peteruithoven** [comment] 2016-03-02 16:10
Ah, we'll close this one then.

**Closed by peteruithoven** 2016-03-02 16:10 UTC
